Init breakthrough
FocusKabinet/focus pull request #12
Opened 2021-05-22 02:38 UTC by DenEdwards

2021-05-22 03:33 UTC, vladislab requested changes

2021-05-22 03:33 UTC, vladislab commented on src/components/IdeaCard.js
> +import React from 'react';
can you revert this file before merging

2021-05-22 20:47 UTC, vladislab submitted a review, later dismissed

2021-05-22 20:48 UTC, vladislab commented
@DenEdwards conflicted oof

2021-05-24 22:39 UTC, DenEdwards commented
That wasn't showing up two days ago?

2021-05-24 22:58 UTC, vladislab commented
idk i approved then it popped up

2021-05-24 23:08 UTC, vladislab approved these changes

2021-05-25 01:55 UTC, closed without merging